# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f adm/Dockerfile-installed-bionic -t sawtooth-admin-tools .

# -------------=== admin tools build ===-------------
FROM hyperledger/sawtooth-dev:v1 as adm-builder

COPY adm /build/adm
COPY protos /build/protos
COPY families/settings/protos /build/families/settings/protos
COPY LICENSE /build/LICENSE

WORKDIR /build/adm

ARG REPO_VERSION
ARG CARGO_ARGS

RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS
RUN mv /build/adm/target/debian/sawtooth-sawadm*.deb /tmp

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== admin tools docker build ===-------------
FROM ubuntu:bionic

ARG CARGO_ARGS
RUN echo "CARGO_ARGS = '$CARGO_ARGS'" > CARGO_ARGS

COPY --from=adm-builder /tmp/sawtooth-sawadm_*.deb /tmp
COPY --from=adm-builder /commit-hash /commit-hash

RUN apt-get update \
 && dpkg --unpack /tmp/sawtooth-sawadm_*.deb \
 && apt-get -f -y install \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
