# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f families/identity/Dockerfile-installed-bionic -t sawtooth-identity-tp .

# -------------=== identity build ===-------------

FROM hyperledger/sawtooth-dev:v1 as identity-tp-builder

COPY families/identity/sawtooth_identity /build/families/identity/sawtooth_identity
COPY families/identity/protos /build/families/identity/protos
COPY protos /build/protos

WORKDIR /build/families/identity/sawtooth_identity

ARG REPO_VERSION
ARG CARGO_ARGS

RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS
RUN mv /build/families/identity/sawtooth_identity/target/debian/sawtooth-identity-tp_*.deb /tmp

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

 # -------------=== identity docker build ===-------------
FROM ubuntu:bionic

COPY --from=identity-tp-builder /tmp/sawtooth-identity-tp_*.deb /tmp
COPY --from=identity-tp-builder /commit-hash /commit-hash

RUN apt-get update \
 && dpkg --unpack /tmp/sawtooth-identity-*.deb \
 && apt-get -f -y install \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
