# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f validator/Dockerfile-installed-bionic -t sawtooth-validator .

# -------------=== validator build ===-------------
FROM hyperledger/sawtooth-dev:v1 as sawtooth-validator-builder

ENV VERSION=AUTO_STRICT

COPY bin/protogen /build/bin/protogen
COPY protos /build/protos
COPY families/settings/protos /build/families/settings/protos
COPY families/identity/protos /build/families/identity/protos
COPY validator /build/validator

ARG REPO_VERSION

RUN /build/bin/protogen \
 && cd /build/validator \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi \
 && if [ -d "bin" ]; then rm -rf bin; fi \
 && mkdir bin \
 && if [ -d "lib" ]; then rm -rf lib; fi \
 && mkdir lib \
 && sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"$REPO_VERSION\"/" Cargo.toml \
 && cargo build --release \
 && cp ./target/release/sawtooth-validator bin/sawtooth-validator \
 && cp ./target/release/libsawtooth_validator.so lib/libsawtooth_validator.so \
 && dpkg-buildpackage -b -rfakeroot -us -uc

 # Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== cli build ===-------------
FROM hyperledger/sawtooth-dev:v1 as sawtooth-cli-builder

ENV VERSION=AUTO_STRICT

COPY . /project

RUN /project/bin/protogen \
 && cd /project/cli \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi \
 && dpkg-buildpackage -b -rfakeroot -us -uc

 # Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== sawtooth-validator docker build ===-------------
FROM ubuntu:bionic

RUN apt-get update \
 && apt-get install -y \
 gnupg \
 systemd

COPY --from=sawtooth-cli-builder /project/python3-sawtooth-cli*.deb /tmp
COPY --from=sawtooth-validator-builder /build/python3-sawtooth-validator*.deb /tmp
COPY --from=sawtooth-validator-builder /commit-hash /commit-hash

RUN echo "deb http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && dpkg --unpack /tmp/python3-sawtooth-*.deb || true \
 && apt-get -f -y install \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
