# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f families/smallbank/smallbank_rust/Dockerfile-installed-bionic -t sawtooth-smallbank-tp-rust .

# -------------=== smallbank rust build ===-------------
FROM hyperledger/sawtooth-dev:v1 as smallbank-rust-builder

COPY families/smallbank/smallbank_rust/ /build/families/smallbank/smallbank_rust
COPY families/smallbank/protos /build/families/smallbank/protos

WORKDIR /build/families/smallbank/smallbank_rust/

ARG REPO_VERSION
ARG CARGO_ARGS

RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS
RUN mv /build/families/smallbank/smallbank_rust/target/debian/sawtooth-smallbank*.deb /tmp

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== smallbank rust docker build ===-------------
FROM ubuntu:bionic

COPY --from=smallbank-rust-builder /tmp/sawtooth-smallbank*.deb /tmp
COPY --from=smallbank-rust-builder /commit-hash /commit-hash

RUN apt-get update \
 && dpkg --unpack /tmp/sawtooth-smallbank*.deb \
 && apt-get -f -y install \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
