# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f perf/smallbank_workload/Dockerfile-installed-bionic -t sawtooth-smallbank-workload .

# -------------=== cli build ===-------------
FROM hyperledger/sawtooth-dev:v1 as cli-builder

ENV VERSION=AUTO_STRICT

COPY . /project

RUN /project/bin/protogen \
 && cd /project/cli \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi \
 && dpkg-buildpackage -b -rfakeroot -us -uc

 # Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== smallbank workload build ===-------------
FROM hyperledger/sawtooth-dev:v1 as smallbank-workload-builder

COPY perf/smallbank_workload/ /build/perf/smallbank_workload
COPY perf/sawtooth_perf /build/perf/sawtooth_perf
COPY families/smallbank/protos /build/families/smallbank/protos

WORKDIR /build/perf/smallbank_workload

ARG REPO_VERSION
ARG CARGO_ARGS

RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS
RUN mv /build/perf/smallbank_workload/target/debian/sawtooth-smallbank-workload*.deb /tmp

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== smallbank workload docker build ===-------------
FROM ubuntu:bionic

RUN apt-get update \
 && apt-get install gnupg -y

COPY --from=cli-builder /project/python3-sawtooth-cli* /tmp
COPY --from=smallbank-workload-builder /tmp/sawtooth-smallbank-workload*.deb /tmp
COPY --from=smallbank-workload-builder /commit-hash /commit-hash

RUN echo "deb http://repo.sawtooth.me/ubuntu/ci bionic universe" >> /etc/apt/sources.list \
 && echo "deb [arch=amd64] http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8AA7AF1F1091A5FD 44FC67F19B2466EA) \
 && apt-get update \
 && apt-get install -y -q \
    python3-sawtooth-sdk \
 && dpkg --unpack /tmp/*sawtooth*.deb || true \
 && apt-get -f -y install
